### ISSUE TITLE
Pass logged in Phone Number as <Party A> and as <PhoneNumber> from firebase Authentication:

### ISSUE THREAD

**Issue by mobisa-012** [flavian-anselmo/mpesa-daraja-plugin-flutter-dart#1]
I have set everythong write and I'm trying to call the user's logged in phone number to propmt Mpesa but it's not working:
Future<void> initiatePayment() async {
  final stk = MpesaDaraja(
    consumerKey: 'my ConsumerKey',
    consumerSecret: 'myConsumerSecret',
    passKey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
  );

  int amount = int.parse(calculatedTotalCost.replaceAll(RegExp(r'[^\d]'), ''));

  final User? user = FirebaseAuth.instance.currentUser;
  String? userPhoneNumber = FirebaseAuth.instance.currentUser?.phoneNumber; // Declare the variable outside the if block

  if (user != null) {
    userPhoneNumber = user.phoneNumber;
  } else {
    // Handle the case where the user is not logged in or phone number is not available.
    // You can show an error message or take appropriate action.
    return;
  }

  await stk.lipaNaMpesaStk(
    "174379",
    amount,
    userPhoneNumber!,
    "174379",
    userPhoneNumber,
    "https://8570-41-80-116-102.ngrok-free.app",
    "FIKISHA RIDERS",
    "transactionDesc",
  );
}

What can I do?
Uisng my phone Number works perfectly.

**Comment by flavian-anselmo** [comment]
helllo @mobisa-012  I will look into this issue and fix it or you can as well contribute on the same. Also are you sure the number is registered since for your  actual number it works ?

**Comment by flavian-anselmo** [comment]
```dart
Future<void> main() async {
  final stk = MpesaDaraja(
    consumerKey: 'Dm4oJgziMyOT7WTmJzQfEZS6jjzg1Fkd',
    consumerSecret: 'RGRvsUGkO4jc3NuW',
    passKey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
  );

  await stk.lipaNaMpesaStk(
    "174379",
    1,
    "254798071520",
    "174379",
    "254798071520",
    "https://mydomain.com/path",
    "accountReference",
    "transactionDesc",
  );
}

```

**Comment by flavian-anselmo** [comment]
did you call this function lipaNaMpesaStk()?

**Comment by mobisa-012** [comment]
Hello @flavian-anselmo 

I solved the issue: I had to format the phone number so that the Mpesa prompt could go through.

**Comment by flavian-anselmo** [comment]
let me close this issue then. Thanks!
